project:
  type: website
  output-dir: docs
website:
  title: posts
  navbar:
    left:
      - about.qmd
      - icon: github
        href: https://github.com/Sass09
      
format:
  html:
    theme: lux
    css: styles.css
    fontcolor: blue
editor: visual

