---
title: "Midterm project part 1"
author: "Shifa Maqsood"
---

Q. Write a blog post where you demonstrate your ability to use these basic programming concepts in R.

**1.**  R objects: show that you understand and can create/use objects of various types, including at least: character/string, numeric, integer, logical, data.frame, and list. Show that you can index objects appropriately (e.g., locate elements of an object, change elements of an object etc.)

**2.**  Logical operations: show that you understand and can use logical operators in R (e.g., == \| \> \< \>= \<=)


**3.**  Loops: Show that you understand the components of a for loop, and that you can use a for loop.

There are three types of loops, for loop, while loop and repeat loops. 
For loop is the commonly used loop.
The syntax is 


```{r}

j <- c(3,6,7,8)
for (i in j ){
  i<- i^2 
  print(i)
}


```

**4.** Functions: Show that you understand the syntax for declaring your own function, and that you can declare and run your own custom function to accomplish some task (you choose what the function does).
