---
title: "Final Report (Tidy Tuesday)"
author: Shifa Maqsood
---

```{r}
library(tidyverse)
library(treemap)

#ArtHistorytidytuesday

tuesdata <- tidytuesdayR::tt_load('2023-01-17')
arthistory <-tuesdata[["artists"]]

count_of_artists <- arthistory %>%
  group_by(year) %>%
  count()

count_of_artistsggplot <- ggplot(count_of_artists, aes(x= year, y=n)) +
  geom_bar(stat="identity",position="dodge", fill="darkgreen") +
  scale_x_continuous(breaks = seq(1925,2025,25))+
  scale_y_continuous(breaks =seq(0,200, 50))+
  ggtitle("Overall Count of Artists in Gardener's Art Throughout the Ages")+
  ylab("Count")+
  xlab("Year of Publication")

count_of_artistsggplot 
```

```{r}
#Alone 

loadouts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-24/loadouts.csv')

popularloadout <- loadouts %>%
  group_by(item) %>%
  count() %>%
treemap(
  index = "item",
  vSize = "n",
  title= "",
  inflate.labels =TRUE
  
)
```

```{r}
age_gaps <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-02-14/age_gaps.csv', show_col_types = FALSE)

#which movies had couples with more than 40 years of age difference? 
highest_age_gap <- age_gaps %>%
select(movie_name,age_difference) %>%
  filter(age_difference > 40)

ggplot(highest_age_gap, aes(movie_name, age_difference))+
  geom_bar(stat = "identity", position = "dodge", fill="#541296" )

  
```
